server:
  port: 9527
spring:
  application:
    name: ZUUL-SERVER		#Zuul网关在Eureka的服务名称，随便取
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka	 #Eureka的注册地址
zuul:
  routes:
    provider.serviceId: TEST-PROVIDER	#没有提示，自己取名称，值为服务的名称
    provider.path: /test/**  #匹配指定的路径，资源匹配的路径才会拦截，转发
    ignored-services: "*"      #忽略直接使用服务名   *忽略所有的服务
    prefix: /server            #统一给访问前缀